# Docker
trigger:
- release
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: WebApp

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'TestApplication1/Dockerfile'
    buildContext: 'TestApplication1'