# Docker
trigger:
- release
pool:
  vmImage: 'windows-2019'

steps:
- task: NuGetCommand@2
  inputs:
    command: restore
- task: MSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildVersion: '16.0'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: WebApp